# -*- coding: utf-8 -*-
"""Shared protocol helpers for the next PSTX agent runtime."""

from .protocol import (
    PROTOCOL_VERSION,
    AgentProtocolError,
    AgentModelStep,
    AgentTodoItem,
    AgentTodoList,
    MemorySummary,
    ObservationBundle,
    ToolBatchCall,
    build_agent_protocol_brief,
    normalize_tool_batch,
    parse_agent_model_step,
)
from .task_dispatch import (
    TASK_DISPATCH_SCHEMA_VERSION,
    DispatchTask,
    compact_dispatch_records,
    normalize_dispatch_tasks,
)
from .subagent import (
    SUBAGENT_SCHEMA_VERSION,
    SubagentDefinition,
    build_subagent_definition,
    build_subagent_question,
    compact_subagent_result,
    plan_subagents,
    summarize_subagent_results,
)
from .memory import build_runtime_state
from .task_ledger import TASK_LEDGER_VERSION, build_task_ledger, todo_list_from_task_ledger
from .goal_contract import EVIDENCE_GOAL_CONTRACT_VERSION, build_evidence_goal_contract
from .executor import execute_runtime_tool_calls, merge_runtime_tool_execution
from .executor import build_tool_error_observation, is_recoverable_tool_error, recommended_tools_for_recovery, tool_call_signature
from .finalizer import (
    AgentFinalizationResult,
    build_perseverance_retry_note,
    build_final_answer_quality_gate,
    citation_items,
    is_low_effort_answer,
    list_of_strings,
    normalize_citations,
    normalize_needs_user_input,
    normalize_proposed_actions,
    status_from_stopped_reason,
)
from .compression import (
    build_evidence_card,
    build_evidence_layers,
    build_context_budget_summary,
    evidence_ids_from_observations,
    fit_items_to_json_budget,
    json_char_count,
    observation_bundle_summary,
)
from .session import PROJECT_SESSION_MEMORY_VERSION, AgentSessionState, build_agent_session_state, merge_project_session_memory
from .evidence_memory import (
    MEMORY_PREFETCH_PLAN_VERSION,
    PROJECT_EVIDENCE_MEMORY_VERSION,
    build_project_evidence_memory,
    compact_project_evidence_memory,
    get_project_evidence_memory_card,
    search_project_evidence_memory,
    select_project_memory_prefetch_tool_calls,
)
from .planner import (
    AgentCapabilityPlan,
    AgentCapabilityProfile,
    allowed_tool_names,
    build_capability_plan,
    build_capability_plan_items,
    dedupe_profile_ids,
    filtered_tool_list,
    infer_capability_profiles,
    list_public_profiles,
    profile_config,
)
from .playbook import (
    AgentPlaybook,
    AgentPlaybookPlan,
    COMPARE_AGENT_PLAYBOOKS,
    REPORT_AGENT_PLAYBOOKS,
    ToolResultContract,
    build_playbook_plan,
    build_tool_result_contract,
)
from .repair import build_quality_repair_tool_calls, filter_auto_quality_repair_tool_calls
from .prefetch import (
    GOAL_PREFETCH_PLAN_VERSION,
    PREFETCH_PLAN_VERSION,
    select_goal_prefetch_tool_calls,
    select_prefetch_followup_tool_calls,
    select_seeded_prefetch_tool_calls,
)
from .effort_policy import EFFORT_POLICY_VERSION, build_effort_policy_retry_note, build_effort_policy_state
from .guidance import GUIDANCE_VERSION, compact_guidance_for_model, find_guidance_files, load_project_guidance
from .kernel import KERNEL_VERSION, build_agentic_envelope, persist_agentic_task_memory, update_agentic_effort
from .skill_registry import SKILL_REGISTRY_VERSION, HarnessSkill, load_harness_skills, select_harness_skills
from .task_memory import TASK_MEMORY_VERSION, read_task_memory, task_memory_path, write_task_memory
from .trace import AgentTraceStore, build_continuation_pack, build_execution_journal, build_journal_summary, build_trace_envelope
from .turn_context import (
    TOOL_DISPATCH_SUMMARY_SCHEMA_VERSION,
    TOOL_DISPATCH_TRACE_SCHEMA_VERSION,
    TURN_CONTEXT_SCHEMA_VERSION,
    build_harness_turn_context_snapshot,
    build_tool_dispatch_event,
    compact_dispatch_args,
    summarize_tool_dispatch_trace,
)
from .workspace import (
    AGENT_SCRATCH_FILES_VERSION,
    AGENT_WORKSPACE_VERSION,
    append_workspace_log,
    agent_workspace_root,
    ensure_scope_workspace,
    list_workspace_artifacts,
    safe_workspace_id,
    scope_workspace,
    workspace_status,
    write_task_markdown,
    write_workspace_artifact,
    write_workspace_draft,
    write_workspace_scratch_files,
)
from .durable_store import DURABLE_RUN_STORE_VERSION, AgentDurableRunStore, new_agent_run_id
from .background import BACKGROUND_RUNNER_VERSION, AgentBackgroundJob, AgentBackgroundRunner
from .checkpoint import CHECKPOINT_REPORTER_VERSION, AgentCheckpointReporter

__all__ = [
    "AgentPlaybook",
    "AgentPlaybookPlan",
    "AgentCapabilityPlan",
    "AgentCapabilityProfile",
    "AgentFinalizationResult",
    "PROTOCOL_VERSION",
    "MEMORY_PREFETCH_PLAN_VERSION",
    "GOAL_PREFETCH_PLAN_VERSION",
    "PREFETCH_PLAN_VERSION",
    "PROJECT_EVIDENCE_MEMORY_VERSION",
    "PROJECT_SESSION_MEMORY_VERSION",
    "AgentProtocolError",
    "AgentSessionState",
    "AgentModelStep",
    "AgentTodoItem",
    "AgentTodoList",
    "AgentTraceStore",
    "MemorySummary",
    "ObservationBundle",
    "COMPARE_AGENT_PLAYBOOKS",
    "REPORT_AGENT_PLAYBOOKS",
    "ToolBatchCall",
    "DispatchTask",
    "SubagentDefinition",
    "ToolResultContract",
    "TASK_LEDGER_VERSION",
    "EVIDENCE_GOAL_CONTRACT_VERSION",
    "EFFORT_POLICY_VERSION",
    "GUIDANCE_VERSION",
    "KERNEL_VERSION",
    "SKILL_REGISTRY_VERSION",
    "TASK_MEMORY_VERSION",
    "TASK_DISPATCH_SCHEMA_VERSION",
    "SUBAGENT_SCHEMA_VERSION",
    "AGENT_SCRATCH_FILES_VERSION",
    "AGENT_WORKSPACE_VERSION",
    "DURABLE_RUN_STORE_VERSION",
    "BACKGROUND_RUNNER_VERSION",
    "CHECKPOINT_REPORTER_VERSION",
    "TURN_CONTEXT_SCHEMA_VERSION",
    "TOOL_DISPATCH_TRACE_SCHEMA_VERSION",
    "TOOL_DISPATCH_SUMMARY_SCHEMA_VERSION",
    "AgentBackgroundJob",
    "AgentBackgroundRunner",
    "AgentCheckpointReporter",
    "AgentDurableRunStore",
    "allowed_tool_names",
    "build_agent_protocol_brief",
    "build_agentic_envelope",
    "build_capability_plan",
    "build_capability_plan_items",
    "build_context_budget_summary",
    "build_continuation_pack",
    "build_evidence_card",
    "build_evidence_layers",
    "build_evidence_goal_contract",
    "build_agent_session_state",
    "build_execution_journal",
    "build_final_answer_quality_gate",
    "build_journal_summary",
    "build_harness_turn_context_snapshot",
    "build_perseverance_retry_note",
    "build_effort_policy_retry_note",
    "build_effort_policy_state",
    "build_playbook_plan",
    "build_project_evidence_memory",
    "build_quality_repair_tool_calls",
    "filter_auto_quality_repair_tool_calls",
    "build_runtime_state",
    "build_task_ledger",
    "build_subagent_definition",
    "build_subagent_question",
    "build_tool_error_observation",
    "build_tool_dispatch_event",
    "build_trace_envelope",
    "build_tool_result_contract",
    "citation_items",
    "dedupe_profile_ids",
    "execute_runtime_tool_calls",
    "evidence_ids_from_observations",
    "fit_items_to_json_budget",
    "filtered_tool_list",
    "compact_project_evidence_memory",
    "compact_dispatch_records",
    "compact_subagent_result",
    "compact_dispatch_args",
    "compact_guidance_for_model",
    "get_project_evidence_memory_card",
    "find_guidance_files",
    "HarnessSkill",
    "infer_capability_profiles",
    "is_low_effort_answer",
    "is_recoverable_tool_error",
    "json_char_count",
    "list_public_profiles",
    "list_of_strings",
    "load_harness_skills",
    "load_project_guidance",
    "normalize_tool_batch",
    "normalize_dispatch_tasks",
    "normalize_citations",
    "normalize_needs_user_input",
    "normalize_proposed_actions",
    "observation_bundle_summary",
    "parse_agent_model_step",
    "plan_subagents",
    "persist_agentic_task_memory",
    "recommended_tools_for_recovery",
    "read_task_memory",
    "search_project_evidence_memory",
    "select_harness_skills",
    "select_goal_prefetch_tool_calls",
    "select_prefetch_followup_tool_calls",
    "select_project_memory_prefetch_tool_calls",
    "select_seeded_prefetch_tool_calls",
    "summarize_subagent_results",
    "summarize_tool_dispatch_trace",
    "tool_call_signature",
    "task_memory_path",
    "update_agentic_effort",
    "merge_project_session_memory",
    "merge_runtime_tool_execution",
    "profile_config",
    "todo_list_from_task_ledger",
    "write_task_memory",
    "append_workspace_log",
    "agent_workspace_root",
    "ensure_scope_workspace",
    "list_workspace_artifacts",
    "new_agent_run_id",
    "safe_workspace_id",
    "scope_workspace",
    "workspace_status",
    "write_task_markdown",
    "write_workspace_artifact",
    "write_workspace_draft",
    "write_workspace_scratch_files",
]
