# -*- coding: utf-8 -*-
"""Public registry for read-only report harness tools."""

from __future__ import annotations

from pstx_harness.report_data_tools import (
    _batch_get_component_identity_cards_tool,
    _batch_get_project_memory_evidence_tool,
    _batch_get_table_rows_tool,
    _batch_match_component_datasheets_tool,
    _batch_query_report_entities_tool,
    _batch_search_feishu_cache_rows_tool,
    _get_evidence_pack_tool,
    _get_project_memory_evidence_tool,
    _get_table_rows_tool,
    _list_project_files_tool,
    _list_project_memory_evidence_tool,
    _list_report_tables_tool,
    _query_report_entity_tool,
    _read_project_text_tool,
    _search_project_text_tool,
    _summarize_schematic_page_count_tool,
    _summarize_table_column_values_tool,
    _trace_project_source_tool,
)
from pstx_harness.report_evidence_tools import (
    _bom_depop_tool,
    _csa_tool,
    _derating_tool,
    _drc_tool,
    _feishu_tool,
    _page_mapping_tool,
    _resistor_tool,
)
from pstx_harness.report_knowledge_tools import (
    _batch_expand_topology_review_tasks_tool,
    _batch_query_chip_topology_tool,
    _batch_query_llm_topology_netlist_tool,
    _batch_search_datasheet_chunks_tool,
    _batch_search_documents_tool,
    _get_agent_ref_pdf_excerpt_tool,
    _get_chip_topology_edge_tool,
    _get_llm_topology_edge_tool,
    _get_llm_topology_node_tool,
    _get_topology_review_task_tool,
    _get_component_identity_card_tool,
    _get_datasheet_chunk_tool,
    _get_datasheet_excerpt_tool,
    _get_datasheet_page_excerpt_tool,
    _get_datasheet_parameter_tool,
    _get_datasheet_review_template_tool,
    _get_document_excerpt_tool,
    _get_feishu_cache_row_tool,
    _get_review_checklist_excerpt_tool,
    _list_agent_ref_sources_tool,
    _list_business_dictionary_tool,
    _list_component_identity_cards_tool,
    _list_datasheet_documents_tool,
    _list_datasheet_review_templates_tool,
    _list_datasheet_sources_tool,
    _list_document_search_sources_tool,
    _list_feishu_cache_libraries_tool,
    _list_review_checklist_sources_tool,
    _match_component_datasheets_tool,
    _query_chip_topology_tool,
    _query_llm_topology_netlist_tool,
    _search_agent_ref_pdfs_tool,
    _search_component_identity_cards_tool,
    _search_datasheet_chunks_tool,
    _search_datasheet_parameters_tool,
    _search_datasheets_tool,
    _search_documents_tool,
    _search_feishu_cache_rows_tool,
    _search_review_checklists_tool,
    _summarize_chip_topology_tool,
    _summarize_llm_topology_netlist_tool,
    _summarize_topology_review_tasks_tool,
    _summarize_dfmea_datasheet_coverage_tool,
    _summarize_dfmea_readiness_tool,
)
from pstx_harness.skill_tools import (
    _get_harness_skill_tool,
    _list_harness_skills_tool,
    _select_harness_skills_tool,
)
from pstx_harness.report_tool_utils import BATCH_DEFAULT_PER_ITEM_LIMIT, BATCH_MAX_ITEMS
from pstx_harness.tool_core import (
    HarnessTool,
    HarnessToolContext,
    HarnessToolError,
    HarnessToolRegistry,
    _schema,
)


__all__ = [
    "DEFAULT_TOOL_ORDER",
    "HarnessTool",
    "HarnessToolContext",
    "HarnessToolError",
    "HarnessToolRegistry",
    "build_default_harness_registry",
]


def build_default_harness_registry() -> HarnessToolRegistry:
    registry = HarnessToolRegistry()
    for tool in [
        HarnessTool("bom_depop", "BOM/DEPOP 与 BOM_OPTION 打圈", "读取 BOM_OPTION、DEPOP 和打圈覆盖结果。", "bom", _bom_depop_tool),
        HarnessTool("page_mapping", "主模块页/页码映射", "读取主模块页到页码的映射检查和页码统计。", "network", _page_mapping_tool),
        HarnessTool("drc", "DRC 属性/网络命名", "读取属性缺失、单节点、未命名和 BOM_OPTION 拼写结果。", "drc", _drc_tool),
        HarnessTool("resistor", "芯片 Pin / 串阻 / 上下拉", "读取芯片 Pin、电阻、上下拉和重复偏置候选结果。", "resistor", _resistor_tool),
        HarnessTool("derating", "电容降额与人工复核边界", "读取电容降额结果和阈值。", "derating", _derating_tool),
        HarnessTool("csa", "CSA 几何规范", "读取 CSA 页级、DOT 和画圈对象结果。", "csa", _csa_tool),
        HarnessTool("feishu_bom", "Feishu BOM 缓存状态", "读取本地 Feishu BOM 配置和 SQLite 缓存状态。", "bom", _feishu_tool),
        HarnessTool(
            "list_project_memory_evidence",
            "项目证据记忆检索",
            "检索当前 run_id 会话内沉淀的 evidence card，帮助多轮对话复用已验证证据。",
            "memory",
            _list_project_memory_evidence_tool,
            input_schema=_schema({
                "query": {"type": "string", "maxLength": 200},
                "evidence_type": {"type": "string", "maxLength": 100},
                "limit": {"type": "integer", "minimum": 1, "maximum": 100},
                "offset": {"type": "integer", "minimum": 0, "maximum": 10000},
            }),
        ),
        HarnessTool(
            "get_project_memory_evidence",
            "读取项目证据记忆详情",
            "按 evidence id 读取当前项目会话内保存的 evidence card。",
            "memory",
            _get_project_memory_evidence_tool,
            input_schema=_schema({
                "evidence_id": {"type": "string", "maxLength": 180},
            }, required=["evidence_id"]),
        ),
        HarnessTool(
            "batch_get_project_memory_evidence",
            "批量读取项目证据记忆",
            "按多个 evidence id 批量读取当前项目会话内保存的 evidence card。",
            "memory",
            _batch_get_project_memory_evidence_tool,
            input_schema=_schema({
                "evidence_ids": {"type": "array", "minItems": 1, "maxItems": BATCH_MAX_ITEMS},
            }, required=["evidence_ids"]),
        ),
        HarnessTool(
            "list_harness_skills",
            "Harness Skill 清单",
            "列出当前仓库内 Harness Agent 可读取的技能卡；技能卡只提供打法指导，不授权新工具。",
            "skill",
            _list_harness_skills_tool,
            input_schema=_schema({
                "include_body": {"type": "boolean"},
                "max_body_chars": {"type": "integer", "minimum": 200, "maximum": 20000},
                "limit": {"type": "integer", "minimum": 1, "maximum": 200},
            }),
            evidence_kind="harness_skill",
        ),
        HarnessTool(
            "select_harness_skills",
            "选择 Harness Skill",
            "按用户问题、能力 profile、playbook 或工具名选择相关技能卡，帮助 Agent 补充取证打法。",
            "skill",
            _select_harness_skills_tool,
            input_schema=_schema({
                "query": {"type": "string", "maxLength": 400},
                "capability_profiles": {"type": "array", "maxItems": 12},
                "playbooks": {"type": "array", "maxItems": 12},
                "tools": {"type": "array", "maxItems": 24},
                "include_body": {"type": "boolean"},
                "max_body_chars": {"type": "integer", "minimum": 200, "maximum": 20000},
                "limit": {"type": "integer", "minimum": 1, "maximum": 24},
            }),
            evidence_kind="harness_skill",
        ),
        HarnessTool(
            "get_harness_skill",
            "读取 Harness Skill",
            "按 skill_id 读取单张技能卡详情；用于在运行中查看推荐工具、证据顺序和输出约束。",
            "skill",
            _get_harness_skill_tool,
            input_schema=_schema({
                "skill_id": {"type": "string", "maxLength": 120},
                "include_body": {"type": "boolean"},
                "max_body_chars": {"type": "integer", "minimum": 200, "maximum": 20000},
            }, required=["skill_id"]),
            evidence_kind="harness_skill",
        ),
        HarnessTool(
            "list_feishu_cache_libraries",
            "飞书缓存库清单",
            "列出本地飞书 SQLite 缓存中的库、Sheet 统计和字段顺序。",
            "bom",
            _list_feishu_cache_libraries_tool,
            input_schema=_schema({
                "include_sheets": {"type": "boolean"},
            }),
        ),
        HarnessTool(
            "search_feishu_cache_rows",
            "搜索飞书缓存物料",
            "按 HQ 料号、规格型号、描述、PI、选型顺序和扩展字段搜索本地飞书缓存。",
            "bom",
            _search_feishu_cache_rows_tool,
            input_schema=_schema({
                "query": {"type": "string", "maxLength": 200},
                "lib_id": {"type": "string", "maxLength": 120},
                "sheet_name": {"type": "string", "maxLength": 160},
                "limit": {"type": "integer", "minimum": 1, "maximum": 100},
                "offset": {"type": "integer", "minimum": 0, "maximum": 100000},
            }, required=["query"]),
        ),
        HarnessTool(
            "get_feishu_cache_row",
            "读取飞书缓存物料详情",
            "按本地缓存行 ID 读取单条飞书物料详情。",
            "bom",
            _get_feishu_cache_row_tool,
            input_schema=_schema({
                "row_id": {"type": "integer", "minimum": 1, "maximum": 100000000},
            }, required=["row_id"]),
        ),
        HarnessTool(
            "batch_search_feishu_cache_rows",
            "批量搜索飞书缓存物料",
            "按多个 HQ 料号、规格、PI 或选型顺序关键词批量搜索本地飞书缓存。",
            "bom",
            _batch_search_feishu_cache_rows_tool,
            input_schema=_schema({
                "queries": {"type": "array", "minItems": 1, "maxItems": BATCH_MAX_ITEMS},
                "lib_id": {"type": "string", "maxLength": 120},
                "sheet_name": {"type": "string", "maxLength": 160},
                "limit_per_query": {"type": "integer", "minimum": 1, "maximum": BATCH_DEFAULT_PER_ITEM_LIMIT},
                "limit": {"type": "integer", "minimum": 1, "maximum": BATCH_DEFAULT_PER_ITEM_LIMIT},
            }, required=["queries"]),
        ),
        HarnessTool(
            "list_component_identity_cards",
            "元件身份卡清单",
            "按类别、位号前缀、HQ 料号和飞书匹配状态分页列出 DFMEA 准备身份卡。",
            "dfmea",
            _list_component_identity_cards_tool,
            input_schema=_schema({
                "category": {"type": "string", "maxLength": 80},
                "refdes_prefix": {"type": "string", "maxLength": 40},
                "hq_no": {"type": "string", "maxLength": 160},
                "feishu_status": {"type": "string", "maxLength": 80},
                "limit": {"type": "integer", "minimum": 1, "maximum": 200},
                "offset": {"type": "integer", "minimum": 0, "maximum": 100000},
            }),
        ),
        HarnessTool(
            "get_component_identity_card",
            "读取元件身份卡详情",
            "按 refdes 读取单个元件的 DFMEA 准备身份卡。",
            "dfmea",
            _get_component_identity_card_tool,
            input_schema=_schema({
                "refdes": {"type": "string", "maxLength": 120},
            }, required=["refdes"]),
        ),
        HarnessTool(
            "search_component_identity_cards",
            "搜索元件身份卡",
            "按位号、HQ 料号、规格、PI、选型顺序或网络名搜索 DFMEA 准备身份卡。",
            "dfmea",
            _search_component_identity_cards_tool,
            input_schema=_schema({
                "query": {"type": "string", "maxLength": 200},
                "category": {"type": "string", "maxLength": 80},
                "limit": {"type": "integer", "minimum": 1, "maximum": 200},
                "offset": {"type": "integer", "minimum": 0, "maximum": 100000},
            }, required=["query"]),
        ),
        HarnessTool(
            "batch_get_component_identity_cards",
            "批量读取元件身份卡",
            "按多个 refdes 批量读取 DFMEA 元件身份卡，并标记缺失上下文。",
            "dfmea",
            _batch_get_component_identity_cards_tool,
            input_schema=_schema({
                "refdes_list": {"type": "array", "minItems": 1, "maxItems": BATCH_MAX_ITEMS},
            }, required=["refdes_list"]),
        ),
        HarnessTool(
            "summarize_dfmea_readiness",
            "DFMEA 准备度摘要",
            "汇总当前项目关键器件的 DFMEA 输入准备度、缺失字段和优先对象。",
            "dfmea",
            _summarize_dfmea_readiness_tool,
            input_schema=_schema({}),
        ),
        HarnessTool(
            "list_business_dictionary",
            "项目业务词典/缩写表",
            "列出拓扑/Agent 使用的接口缩写、角色同义词和 review focus 词典。",
            "topology",
            _list_business_dictionary_tool,
            input_schema=_schema({}),
        ),
        HarnessTool(
            "summarize_chip_topology",
            "芯片级连接拓扑摘要",
            "抽取 U/PU/XU 等芯片节点之间的共享信号网络，生成模糊大拓扑关系。",
            "topology",
            _summarize_chip_topology_tool,
            input_schema=_schema({
                "focus_refdes": {"type": "string", "maxLength": 120},
                "role_filter": {"type": "string", "maxLength": 80},
                "include_connectors": {"type": "boolean"},
                "limit": {"type": "integer", "minimum": 1, "maximum": 100},
                "view": {"type": "string", "enum": ["summary", "full"]},
                "supply_mode": {"type": "string", "enum": ["grouped", "details", "hidden"]},
                "supply_limit": {"type": "integer", "minimum": 0, "maximum": 250},
            }),
        ),
        HarnessTool(
            "summarize_llm_topology_netlist",
            "LLM 拓扑网表摘要",
            "输出芯片级 LLM 语义拓扑网表的摘要层、证据卡层和可追溯 detail tool。",
            "topology",
            _summarize_llm_topology_netlist_tool,
            input_schema=_schema({
                "focus_refdes": {"type": "string", "maxLength": 120},
                "role_filter": {"type": "string", "maxLength": 80},
                "include_connectors": {"type": "boolean"},
                "limit": {"type": "integer", "minimum": 1, "maximum": 100},
                "view": {"type": "string", "enum": ["summary", "full"]},
                "supply_mode": {"type": "string", "enum": ["grouped", "details", "hidden"]},
                "supply_limit": {"type": "integer", "minimum": 0, "maximum": 250},
            }),
        ),
        HarnessTool(
            "summarize_topology_review_tasks",
            "拓扑 review 任务队列",
            "按 review 优先级列出芯片/供电/接口拓扑复核任务，适合 Agent 先选任务再二次取证。",
            "topology",
            _summarize_topology_review_tasks_tool,
            input_schema=_schema({
                "focus_refdes": {"type": "string", "maxLength": 120},
                "interface_group": {"type": "string", "maxLength": 80},
                "priority": {"type": "string", "maxLength": 40},
                "include_connectors": {"type": "boolean"},
                "limit": {"type": "integer", "minimum": 1, "maximum": 100},
            }),
        ),
        HarnessTool(
            "query_chip_topology",
            "查询芯片级连接拓扑",
            "按位号、芯片角色、电平转换、接口类型或网络名查询芯片级拓扑关系。",
            "topology",
            _query_chip_topology_tool,
            input_schema=_schema({
                "query": {"type": "string", "maxLength": 240},
                "include_connectors": {"type": "boolean"},
                "limit": {"type": "integer", "minimum": 1, "maximum": 100},
            }, required=["query"]),
        ),
        HarnessTool(
            "query_llm_topology_netlist",
            "查询 LLM 拓扑网表",
            "按位号、角色、接口、网络或 review 关键词查询 LLM 语义拓扑节点和边。",
            "topology",
            _query_llm_topology_netlist_tool,
            input_schema=_schema({
                "query": {"type": "string", "maxLength": 240},
                "include_connectors": {"type": "boolean"},
                "limit": {"type": "integer", "minimum": 1, "maximum": 100},
            }, required=["query"]),
        ),
        HarnessTool(
            "get_llm_topology_node",
            "读取 LLM 拓扑节点详情",
            "按 refdes 读取 LLM 拓扑节点的完整 pin/net、原始 net nodes 和关联边。",
            "topology",
            _get_llm_topology_node_tool,
            input_schema=_schema({
                "refdes": {"type": "string", "maxLength": 120},
                "include_connectors": {"type": "boolean"},
                "max_pin_nets": {"type": "integer", "minimum": 1, "maximum": 1000},
            }, required=["refdes"]),
        ),
        HarnessTool(
            "get_chip_topology_edge",
            "读取芯片级连接详情",
            "按 edge_id 读取一条芯片级连接关系的共享网络、接口类型和两端 pin 摘要。",
            "topology",
            _get_chip_topology_edge_tool,
            input_schema=_schema({
                "edge_id": {"type": "string", "maxLength": 180},
                "include_connectors": {"type": "boolean"},
            }, required=["edge_id"]),
        ),
        HarnessTool(
            "get_llm_topology_edge",
            "读取 LLM 拓扑连接详情",
            "按 edge_id 读取 LLM 拓扑连接的共享网络、一跳无源桥、pin 样本和 review hints。",
            "topology",
            _get_llm_topology_edge_tool,
            input_schema=_schema({
                "edge_id": {"type": "string", "maxLength": 180},
                "include_connectors": {"type": "boolean"},
            }, required=["edge_id"]),
        ),
        HarnessTool(
            "get_topology_review_task",
            "读取拓扑 review task 详情",
            "按 task_id 读取拓扑复核任务及关联节点/边的原始 pin-net 详情。",
            "topology",
            _get_topology_review_task_tool,
            input_schema=_schema({
                "task_id": {"type": "string", "maxLength": 220},
                "include_connectors": {"type": "boolean"},
            }, required=["task_id"]),
        ),
        HarnessTool(
            "batch_query_chip_topology",
            "批量查询芯片级拓扑",
            "按多个位号、角色、网络或接口关键词批量查询芯片级拓扑关系。",
            "topology",
            _batch_query_chip_topology_tool,
            input_schema=_schema({
                "queries": {"type": "array", "minItems": 1, "maxItems": BATCH_MAX_ITEMS},
                "include_connectors": {"type": "boolean"},
                "limit_per_query": {"type": "integer", "minimum": 1, "maximum": 20},
                "limit": {"type": "integer", "minimum": 1, "maximum": 20},
            }, required=["queries"]),
        ),
        HarnessTool(
            "batch_query_llm_topology_netlist",
            "批量查询 LLM 拓扑网表",
            "按多个位号、接口、网络或角色关键词批量查询 LLM 拓扑网表。",
            "topology",
            _batch_query_llm_topology_netlist_tool,
            input_schema=_schema({
                "queries": {"type": "array", "minItems": 1, "maxItems": BATCH_MAX_ITEMS},
                "include_connectors": {"type": "boolean"},
                "limit_per_query": {"type": "integer", "minimum": 1, "maximum": 20},
                "limit": {"type": "integer", "minimum": 1, "maximum": 20},
            }, required=["queries"]),
        ),
        HarnessTool(
            "batch_expand_topology_review_tasks",
            "批量展开拓扑 review task",
            "按多个 task_id 批量读取拓扑复核任务和关联 detail，避免 Agent 逐条循环取证。",
            "topology",
            _batch_expand_topology_review_tasks_tool,
            input_schema=_schema({
                "task_ids": {"type": "array", "minItems": 1, "maxItems": BATCH_MAX_ITEMS},
                "include_connectors": {"type": "boolean"},
            }, required=["task_ids"]),
        ),
        HarnessTool(
            "list_document_search_sources",
            "本地文档搜索状态",
            "列出 harness 文档搜索根目录、可搜索文件数量和支持格式。",
            "document_search",
            _list_document_search_sources_tool,
            input_schema=_schema({}),
        ),
        HarnessTool(
            "search_documents",
            "搜索本地文档",
            "按关键词搜索本地文档，并返回命中文档、行号、字符位置和上下文摘要。",
            "document_search",
            _search_documents_tool,
            input_schema=_schema({
                "query": {"type": "string", "maxLength": 240},
                "limit": {"type": "integer", "minimum": 1, "maximum": 100},
                "max_files": {"type": "integer", "minimum": 1, "maximum": 5000},
            }, required=["query"]),
        ),
        HarnessTool(
            "get_document_excerpt",
            "读取文档命中片段",
            "按 doc_id 和字符位置读取命中附近上下文，用于二次取证。",
            "document_search",
            _get_document_excerpt_tool,
            input_schema=_schema({
                "doc_id": {"type": "string", "maxLength": 80},
                "char_start": {"type": "integer", "minimum": 0, "maximum": 100000000},
                "before_chars": {"type": "integer", "minimum": 0, "maximum": 20000},
                "after_chars": {"type": "integer", "minimum": 1, "maximum": 40000},
                "max_chars": {"type": "integer", "minimum": 1, "maximum": 20000},
            }, required=["doc_id"]),
        ),
        HarnessTool(
            "batch_search_documents",
            "批量搜索本地文档",
            "按多个关键词批量搜索本地文档，返回每项 found/missing 和命中片段。",
            "document_search",
            _batch_search_documents_tool,
            input_schema=_schema({
                "queries": {"type": "array", "minItems": 1, "maxItems": BATCH_MAX_ITEMS},
                "limit_per_query": {"type": "integer", "minimum": 1, "maximum": 20},
                "limit": {"type": "integer", "minimum": 1, "maximum": 20},
            }, required=["queries"]),
        ),
        HarnessTool(
            "list_datasheet_sources",
            "本地规格书索引状态",
            "查看本地 datasheet PDF 目录、索引数量、失败统计和最近更新时间。",
            "dfmea",
            _list_datasheet_sources_tool,
            input_schema=_schema({}),
        ),
        HarnessTool(
            "list_datasheet_review_templates",
            "Datasheet 审查模板清单",
            "列出 LLM 可读的 datasheet 审查模板，说明应抽取哪些参数、需要哪些原理图证据和输出约束。",
            "dfmea",
            _list_datasheet_review_templates_tool,
            input_schema=_schema({
                "category": {"type": "string", "maxLength": 80},
                "include_questions": {"type": "boolean"},
            }),
        ),
        HarnessTool(
            "get_datasheet_review_template",
            "读取 Datasheet 审查模板",
            "按 template_id 读取完整审查模板，用于 datasheet/DFMEA/原理图 review 的取证规划。",
            "dfmea",
            _get_datasheet_review_template_tool,
            input_schema=_schema({
                "template_id": {"type": "string", "maxLength": 80},
            }, required=["template_id"]),
        ),
        HarnessTool(
            "list_datasheet_documents",
            "本地规格书文档清单",
            "列出已索引 datasheet PDF、页数、chunk 数、抽取状态和失败原因。",
            "dfmea",
            _list_datasheet_documents_tool,
            input_schema=_schema({
                "limit": {"type": "integer", "minimum": 1, "maximum": 1000},
                "offset": {"type": "integer", "minimum": 0, "maximum": 100000},
            }),
        ),
        HarnessTool(
            "search_datasheet_chunks",
            "搜索本地规格书片段",
            "按问题、HQ 料号、规格型号、芯片型号和参数关键词搜索可引用 PDF chunk。",
            "dfmea",
            _search_datasheet_chunks_tool,
            input_schema=_schema({
                "query": {"type": "string", "maxLength": 300},
                "limit": {"type": "integer", "minimum": 1, "maximum": 100},
                "offset": {"type": "integer", "minimum": 0, "maximum": 100000},
            }, required=["query"]),
        ),
        HarnessTool(
            "search_datasheet_parameters",
            "搜索规格书参数卡",
            "搜索确定性抽取出的 datasheet 参数卡，如电压、电流、热、时序和环境参数。",
            "dfmea",
            _search_datasheet_parameters_tool,
            input_schema=_schema({
                "query": {"type": "string", "maxLength": 240},
                "parameter_key": {"type": "string", "maxLength": 120},
                "doc_id": {"type": "integer", "minimum": 1, "maximum": 100000000},
                "limit": {"type": "integer", "minimum": 1, "maximum": 200},
                "offset": {"type": "integer", "minimum": 0, "maximum": 100000},
            }),
        ),
        HarnessTool(
            "get_datasheet_parameter",
            "读取规格书参数卡",
            "按 parameter_id 读取完整参数卡和原始来源文本，用于定量参数结论二次取证。",
            "dfmea",
            _get_datasheet_parameter_tool,
            input_schema=_schema({
                "parameter_id": {"type": "integer", "minimum": 1, "maximum": 100000000},
                "max_chars": {"type": "integer", "minimum": 1, "maximum": 12000},
            }, required=["parameter_id"]),
        ),
        HarnessTool(
            "get_datasheet_chunk",
            "读取规格书 chunk",
            "按 doc_id 和 chunk_id 读取完整 PDF chunk，用于定量参数和高风险结论二次取证。",
            "dfmea",
            _get_datasheet_chunk_tool,
            input_schema=_schema({
                "doc_id": {"type": "integer", "minimum": 1, "maximum": 100000000},
                "chunk_id": {"type": "string", "maxLength": 120},
                "max_chars": {"type": "integer", "minimum": 1, "maximum": 12000},
            }, required=["doc_id", "chunk_id"]),
        ),
        HarnessTool(
            "get_datasheet_page_excerpt",
            "读取规格书页片段",
            "兼容按 doc_id 和 page 读取受限长度的本地规格书文本页片段。",
            "dfmea",
            _get_datasheet_page_excerpt_tool,
            input_schema=_schema({
                "doc_id": {"type": "integer", "minimum": 1, "maximum": 100000000},
                "page": {"type": "integer", "minimum": 1, "maximum": 100000},
                "max_chars": {"type": "integer", "minimum": 1, "maximum": 12000},
            }, required=["doc_id", "page"]),
        ),
        HarnessTool(
            "batch_search_datasheet_chunks",
            "批量搜索本地规格书片段",
            "按多个关键词、HQ 料号、规格型号或元件候选一次性检索 PDF chunk。",
            "dfmea",
            _batch_search_datasheet_chunks_tool,
            input_schema=_schema({
                "queries": {"type": "array", "minItems": 1, "maxItems": BATCH_MAX_ITEMS},
                "limit_per_query": {"type": "integer", "minimum": 1, "maximum": BATCH_DEFAULT_PER_ITEM_LIMIT},
                "limit": {"type": "integer", "minimum": 1, "maximum": BATCH_DEFAULT_PER_ITEM_LIMIT},
            }, required=["queries"]),
        ),
        HarnessTool(
            "search_datasheets",
            "搜索本地规格书",
            "按 HQ 料号、规格型号、芯片型号、PI、选型顺序或用户关键词搜索本地 PDF 页级片段。",
            "dfmea",
            _search_datasheets_tool,
            input_schema=_schema({
                "query": {"type": "string", "maxLength": 240},
                "limit": {"type": "integer", "minimum": 1, "maximum": 100},
                "offset": {"type": "integer", "minimum": 0, "maximum": 100000},
            }, required=["query"]),
        ),
        HarnessTool(
            "get_datasheet_excerpt",
            "读取规格书片段",
            "按 doc_id 和 page 读取受限长度的本地规格书文本片段。",
            "dfmea",
            _get_datasheet_excerpt_tool,
            input_schema=_schema({
                "doc_id": {"type": "integer", "minimum": 1, "maximum": 100000000},
                "page": {"type": "integer", "minimum": 1, "maximum": 100000},
                "max_chars": {"type": "integer", "minimum": 1, "maximum": 12000},
            }, required=["doc_id", "page"]),
        ),
        HarnessTool(
            "match_component_datasheets",
            "匹配元件规格书",
            "基于元件身份卡的 HQ 料号、规格和候选芯片类型匹配本地规格书。",
            "dfmea",
            _match_component_datasheets_tool,
            input_schema=_schema({
                "refdes": {"type": "string", "maxLength": 120},
                "limit": {"type": "integer", "minimum": 1, "maximum": 50},
            }, required=["refdes"]),
        ),
        HarnessTool(
            "batch_match_component_datasheets",
            "批量匹配元件规格书",
            "基于多个元件身份卡批量匹配本地规格书候选和缺口。",
            "dfmea",
            _batch_match_component_datasheets_tool,
            input_schema=_schema({
                "refdes_list": {"type": "array", "minItems": 1, "maxItems": BATCH_MAX_ITEMS},
                "limit_per_component": {"type": "integer", "minimum": 1, "maximum": BATCH_DEFAULT_PER_ITEM_LIMIT},
                "limit": {"type": "integer", "minimum": 1, "maximum": BATCH_DEFAULT_PER_ITEM_LIMIT},
            }, required=["refdes_list"]),
        ),
        HarnessTool(
            "summarize_dfmea_datasheet_coverage",
            "DFMEA 规格书覆盖摘要",
            "汇总关键器件的本地规格书匹配覆盖和缺口。",
            "dfmea",
            _summarize_dfmea_datasheet_coverage_tool,
            input_schema=_schema({
                "limit": {"type": "integer", "minimum": 1, "maximum": 100},
            }),
        ),
        HarnessTool(
            "list_agent_ref_sources",
            "Agent Lab ref PDF 索引状态",
            "查看 Agent Lab 默认 ref/ 文件夹、PDF 数量、索引数量和失败统计。",
            "agent_ref",
            _list_agent_ref_sources_tool,
            input_schema=_schema({}),
        ),
        HarnessTool(
            "search_agent_ref_pdfs",
            "搜索 Agent Lab ref PDF",
            "按用户关键词搜索 ref/ 文件夹中的 PDF 页级片段，用于测试 Agent 参考资料读取能力。",
            "agent_ref",
            _search_agent_ref_pdfs_tool,
            input_schema=_schema({
                "query": {"type": "string", "maxLength": 240},
                "limit": {"type": "integer", "minimum": 1, "maximum": 100},
                "offset": {"type": "integer", "minimum": 0, "maximum": 100000},
            }, required=["query"]),
        ),
        HarnessTool(
            "get_agent_ref_pdf_excerpt",
            "读取 Agent Lab ref PDF 片段",
            "按 doc_id 和 page 读取 ref PDF 的受限文本片段。",
            "agent_ref",
            _get_agent_ref_pdf_excerpt_tool,
            input_schema=_schema({
                "doc_id": {"type": "integer", "minimum": 1, "maximum": 100000000},
                "page": {"type": "integer", "minimum": 1, "maximum": 100000},
                "max_chars": {"type": "integer", "minimum": 1, "maximum": 12000},
            }, required=["doc_id", "page"]),
        ),
        HarnessTool(
            "list_review_checklist_sources",
            "Review checklist 索引状态",
            "查看 ref_checklist/ 审查经验清单目录、文件数量、索引数量和失败统计。",
            "review_checklist",
            _list_review_checklist_sources_tool,
            input_schema=_schema({}),
        ),
        HarnessTool(
            "search_review_checklists",
            "搜索 Review checklist",
            "按用户问题搜索 ref_checklist/ 中的真实 review 问题、Excel 记录或 changelist 片段。",
            "review_checklist",
            _search_review_checklists_tool,
            input_schema=_schema({
                "query": {"type": "string", "maxLength": 240},
                "limit": {"type": "integer", "minimum": 1, "maximum": 100},
                "offset": {"type": "integer", "minimum": 0, "maximum": 100000},
            }, required=["query"]),
        ),
        HarnessTool(
            "get_review_checklist_excerpt",
            "读取 Review checklist 片段",
            "按 doc_id 和 page/chunk 读取 ref_checklist 审查经验清单的受限文本片段。",
            "review_checklist",
            _get_review_checklist_excerpt_tool,
            input_schema=_schema({
                "doc_id": {"type": "integer", "minimum": 1, "maximum": 100000000},
                "page": {"type": "integer", "minimum": 1, "maximum": 100000},
                "max_chars": {"type": "integer", "minimum": 1, "maximum": 12000},
            }, required=["doc_id", "page"]),
        ),
        HarnessTool("list_report_tables", "报告表格清单", "列出当前报告中可查询的表格。", "summary", _list_report_tables_tool),
        HarnessTool(
            "summarize_schematic_page_count",
            "统计原理图总页数",
            "从当前项目 module_order(.dat) 计算用户看到的原理图总页数；这里的总页数按页码口径统计，不要用 page_rows 行数替代。",
            "summary",
            _summarize_schematic_page_count_tool,
            input_schema=_schema({}),
            file_access=True,
        ),
        HarnessTool(
            "get_table_rows",
            "读取报告表格行",
            "按 table_id 读取当前报告中的表格行；单次只读一个窗口，更多行请使用返回的 next_offset 继续分页。",
            "summary",
            _get_table_rows_tool,
            input_schema=_schema({
                "table_id": {"type": "string", "maxLength": 120},
                "limit": {"type": "integer", "minimum": 1, "maximum": 200},
                "offset": {"type": "integer", "minimum": 0, "maximum": 100000},
            }, required=["table_id"]),
        ),
        HarnessTool(
            "summarize_table_column_values",
            "统计报告表格列唯一值",
            "按 table_id 和 column 在本地统计总行数、非空行、唯一值数量和 top values，适合页数/覆盖范围等聚合问题。",
            "summary",
            _summarize_table_column_values_tool,
            input_schema=_schema({
                "table_id": {"type": "string", "maxLength": 120},
                "column": {"type": "string", "maxLength": 120},
                "operation": {"type": "string", "enum": ["top", "count", "unique"]},
                "limit_values": {"type": "integer", "minimum": 1, "maximum": 1000},
                "sample_per_value": {"type": "integer", "minimum": 0, "maximum": 5},
                "include_empty": {"type": "boolean"},
            }, required=["table_id", "column"]),
        ),
        HarnessTool(
            "batch_get_table_rows",
            "批量读取报告表格行",
            "一次读取多个报告表格片段；limit_per_request 是单个片段窗口上限，更多行请按每项 next_offset 继续分页。",
            "summary",
            _batch_get_table_rows_tool,
            input_schema=_schema({
                "requests": {"type": "array", "minItems": 1, "maxItems": BATCH_MAX_ITEMS},
                "limit_per_request": {
                    "type": "integer",
                    "minimum": 1,
                    "maximum": BATCH_DEFAULT_PER_ITEM_LIMIT,
                    "coerceMaximum": True,
                },
            }, required=["requests"]),
        ),
        HarnessTool(
            "query_report_entity",
            "查询元件或网络",
            "按位号或网络名查询当前报告对象。",
            "summary",
            _query_report_entity_tool,
            input_schema=_schema({
                "mode": {"type": "string", "enum": ["位号", "网络"]},
                "keyword": {"type": "string", "maxLength": 200},
            }, required=["mode", "keyword"]),
        ),
        HarnessTool(
            "batch_query_report_entities",
            "批量查询报告实体",
            "批量查询多个位号、网络、HQ 料号、页码或报告表内容关键词。",
            "summary",
            _batch_query_report_entities_tool,
            input_schema=_schema({
                "queries": {"type": "array", "minItems": 1, "maxItems": BATCH_MAX_ITEMS},
                "mode": {"type": "string", "enum": ["auto", "自动", "位号", "网络"]},
                "limit_per_query": {"type": "integer", "minimum": 1, "maximum": BATCH_DEFAULT_PER_ITEM_LIMIT},
                "limit": {"type": "integer", "minimum": 1, "maximum": BATCH_DEFAULT_PER_ITEM_LIMIT},
            }, required=["queries"]),
        ),
        HarnessTool(
            "get_evidence_pack",
            "读取证据包",
            "按证据包 ID 读取固定审查证据。",
            "summary",
            _get_evidence_pack_tool,
            input_schema=_schema({
                "pack_id": {
                    "type": "string",
                    "enum": ["bom_depop", "page_mapping", "drc", "resistor", "derating", "csa", "feishu_bom"],
                },
            }, required=["pack_id"]),
        ),
        HarnessTool(
            "list_project_files",
            "项目只读文件清单",
            "列出当前项目根目录下 harness 允许读取的文本文件。",
            "summary",
            _list_project_files_tool,
            input_schema=_schema({
                "limit": {"type": "integer", "minimum": 1, "maximum": 500},
            }),
            file_access=True,
        ),
        HarnessTool(
            "read_project_text",
            "读取项目文本文件",
            "读取当前项目根目录内白名单范围的文本文件片段。",
            "summary",
            _read_project_text_tool,
            input_schema=_schema({
                "path": {"type": "string", "maxLength": 1000},
                "max_chars": {"type": "integer", "minimum": 1, "maximum": 50000},
                "line_start": {"type": "integer", "minimum": 1, "maximum": 1000000},
                "line_count": {"type": "integer", "minimum": 1, "maximum": 500},
                "query": {"type": "string", "maxLength": 500},
                "context_lines": {"type": "integer", "minimum": 0, "maximum": 20},
            }, required=["path"]),
            file_access=True,
        ),
        HarnessTool(
            "search_project_text",
            "搜索项目原始文本",
            "在当前项目根目录内白名单文本文件中做受控 grep，返回行号上下文和可精读 detail_tool。",
            "source",
            _search_project_text_tool,
            input_schema=_schema({
                "query": {"type": "string", "maxLength": 500},
                "mode": {"type": "string", "enum": ["literal", "regex"]},
                "term_mode": {"type": "string", "enum": ["any", "all", "phrase"]},
                "case_sensitive": {"type": "boolean"},
                "path_prefix": {"type": "string", "maxLength": 500},
                "file_glob": {"type": "string", "maxLength": 500},
                "suffixes": {"type": "array", "maxItems": 12, "items": {"type": "string", "maxLength": 20}},
                "context_lines": {"type": "integer", "minimum": 0, "maximum": 20},
                "limit": {"type": "integer", "minimum": 1, "maximum": 100},
                "offset": {"type": "integer", "minimum": 0, "maximum": 1000000},
                "max_files": {"type": "integer", "minimum": 1, "maximum": 2000},
                "max_file_bytes": {"type": "integer", "minimum": 1024, "maximum": 52428800},
            }, required=["query"]),
            file_access=True,
            evidence_kind="source_trace",
        ),
        HarnessTool(
            "trace_project_source",
            "追溯原始项目文件",
            "从位号、网络、页码、报告行或指定文件行定位 PSTX/Cadence 原始文本片段。",
            "source",
            _trace_project_source_tool,
            input_schema=_schema({
                "query": {"type": "string", "maxLength": 500},
                "kind": {"type": "string", "enum": ["auto", "refdes", "net", "page", "text"]},
                "table_id": {"type": "string", "maxLength": 120},
                "row_index": {"type": "integer", "minimum": 0, "maximum": 1000000},
                "row_number": {"type": "integer", "minimum": 1, "maximum": 1000000},
                "path": {"type": "string", "maxLength": 1000},
                "line_start": {"type": "integer", "minimum": 1, "maximum": 1000000},
                "line_count": {"type": "integer", "minimum": 1, "maximum": 500},
                "context_lines": {"type": "integer", "minimum": 0, "maximum": 20},
                "limit": {"type": "integer", "minimum": 1, "maximum": 30},
            }),
            file_access=True,
            evidence_kind="source_trace",
        ),
    ]:
        registry.register(tool)
    return registry


DEFAULT_TOOL_ORDER = [
    "bom_depop",
    "page_mapping",
    "drc",
    "resistor",
    "derating",
    "csa",
    "feishu_bom",
    "summarize_llm_topology_netlist",
    "summarize_topology_review_tasks",
]
